services:
  backend:
    build: .
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=secret
      - DB_NAME=eq
      - DB_PARAMS=sslmode=disable
    depends_on:
      - db
    ports:
      - 8080:8080

  db:
    image: postgres:16-alpine
    restart: always
    command: postgres -c 'max_connections=10'
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: eq
    ports:
      - 5432:5432
    
  migarte: 
    image: migrate/migrate
    volumes:
      - ./db/migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://postgres:secret@db:5432/eq?sslmode=disable", "up"]
    depends_on:
      - db